VirtualSchoolServiceApp/Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VirtualSchoolServiceApp.Models
{
    public class Student
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string AppUserId { get; set; }
        [ForeignKey("AppUserId")]
        public ApplicationUser User { get; set; }

        public int? ClassId { get; set; }
        [ForeignKey("ClassId")]
        public Class? Class { get; set; }
        public List<Grade>? Grades { get; set; } = new List<Grade>();
        public Parent? Parent { get; set; }
    }
    public class StudentVM
    {
        public int Id { get; set; }
        public ApplicationUser User { get; set; }
    }

}

VirtualSchoolServiceApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using VirtualSchoolServiceApp.Data;
using VirtualSchoolServiceApp.Models;

namespace VirtualSchoolServiceApp.Controllers
{
	[Authorize(Roles = "Teacher")]
	public class StudentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public StudentController(ApplicationDbContext db)
        {
            _db = db;

        }

        public IActionResult Index()
        {
            IEnumerable<Student> objStudentsList = _db.Students.Include(s => s.Class).Include(s => s.User);
            return View(objStudentsList);
        }

        public IActionResult StudentGrades(int? id)
        {
            return View();
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAllGrades(int? id)
        {
            var gradeList = _db.Grades.Include(g => g.Subject).Where(g => g.StudentId == id);
            return Json(new { data = gradeList });
        }

        #endregion
    }
}

VirtualSchoolServiceApp/Views/Student/Index.cshtml
@model IEnumerable<Student>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Students List</h2>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    First name
                </th>
                <th>
                    Last name
                </th>
                <th>
                    Class name
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="30%">
                        @obj.User.FirstName
                    </td>
                    <td width="30%">
                        @obj.User.LastName
                    </td>
                    <td width="30%">
                        @obj.Class.Name
                    </td>
                    <td>
                        <div class="w-15 btn-group" role="group">
                            <a asp-controller="Student" asp-action="StudentGrades" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> See degrees</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

VirtualSchoolServiceApp/Views/Student/StudentGrades.cshtml
@{
    ViewData["Title"] = "Student Grades";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Student Grades List</h2>
        </div>
    </div>
    <br />
    <table border="0" cellspacing="5" cellpadding="5">
        <tbody><tr>
            <td>Minimum date:</td>
            <td><input type="text" id="min" name="min"></td>
        </tr>
        <tr>
            <td>Maximum date:</td>
            <td><input type="text" id="max" name="max"></td>
        </tr>
    </tbody></table>
    <table  id="tblData"  class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Mark</th>
                <th>Datetime</th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/studentGrades.js"></script>
}