VirtualSchoolServiceApp/Controllers/AnnoucementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VirtualSchoolServiceApp.Data;
using VirtualSchoolServiceApp.Models;

namespace VirtualSchoolServiceApp.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class AnnoucementController : Controller
    {
        private readonly ApplicationDbContext _db;
		private readonly IEmailSender _emailSender;

		public AnnoucementController(ApplicationDbContext db, IEmailSender emailSender)
        {
            _db = db;
            _emailSender = emailSender;

        }

        public IActionResult Index()
        {
            IEnumerable<Annoucement> objAnnoucementsList = _db.Annoucements.Include(a => a.Teacher).ToList();
            return View(objAnnoucementsList);
        }

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AnnoucementVM obj)
        {
            if (ModelState.IsValid)
            {
                var user = User.Identity.Name;
                ApplicationUser applicationUser = _db.ApplicationUsers.Include(a => a.Teacher).ThenInclude(t => t.Class).First(u => u.UserName == user);

                Annoucement annoucement = new Annoucement()
                {
                    Teacher = applicationUser.Teacher,
                    Content = obj.Content,
                    Title = obj.Title
                };
                _db.Annoucements.Add(annoucement);

                _db.SaveChanges();
                foreach (var parent in _db.Parents.Include(p => p.User))
                {
                    _emailSender.SendEmailAsync(parent.User.Email,
                        "Annoucement from:  " + applicationUser,
                        obj.Content);
                }
				return RedirectToAction("Index");
            }
            return View(obj);
        }
        // GET
        public IActionResult Detail(int? id)
        {
            var annoucement = _db.Annoucements.First(m => m.Id == id);

            return View(annoucement);
        }
    }
}

VirtualSchoolServiceApp/Controllers/GradeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Data;
using VirtualSchoolServiceApp.Data;
using VirtualSchoolServiceApp.Models;


namespace VirtualSchoolServiceApp.Controllers
{
    [Authorize(Roles = "Teacher, Administrator, Parent")]
    public class GradeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public GradeController(ApplicationDbContext db)
        {
            _db = db;
        }
        
        public IActionResult ParentIndex()
        {
            List<GradeVM> objGradeVMList = new List<GradeVM>();
            var user = User.Identity.Name;
            ApplicationUser applicationUser = _db.ApplicationUsers.Include(a => a.Student).First(u => u.UserName == user);
            foreach (var subject in _db.Subjects)
            {
                GradeVM gradeVM = new()
                {
                    Subject = subject,
                    Grades = _db.Grades.Where(g => g.StudentId == applicationUser.Student.Id && g.SubjectId == subject.Id).ToList(),
                    Student = applicationUser.Student
              
                };
                objGradeVMList.Add(gradeVM);
            }

            return View(objGradeVMList);
        }

        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Index()
        {
            IEnumerable<Grade> objGradeList = _db.Grades.Include(g => g.Student).Include(g => g.Subject).ThenInclude(s => s.Teacher).ToList();
            return View(objGradeList);
        }

        // GET
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Create()
        {
            ViewData["Students"] = new SelectList(_db.Set<Student>().Include(s => s.User), "Id", "User");
            ViewData["Subjects"] = new SelectList(_db.Set<Subject>(), "Id", "Name");
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Create(Grade obj)
        {
            if (ModelState.IsValid)
            {
                _db.Grades.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["Students"] = new SelectList(_db.Set<Student>().Include(s => s.User), "Id", "User");
            ViewData["Subjects"] = new SelectList(_db.Set<Subject>(), "Id", "Name");
            return View(obj);
        }

        // GET
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var grade = _db.Grades.Find(id);

            if (grade == null)
            {
                return NotFound();
            }
            ViewData["Students"] = new SelectList(_db.Set<Student>().Include(s => s.User), "Id", "User");
            ViewData["Subjects"] = new SelectList(_db.Set<Subject>(), "Id", "Name");
            return View(grade);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Edit(Grade obj)
        {
            if (ModelState.IsValid)
            {
                _db.Grades.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["Students"] = new SelectList(_db.Set<Student>().Include(s => s.User), "Id", "User");
            ViewData["Subjects"] = new SelectList(_db.Set<Subject>(), "Id", "Name");
            return View(obj);
        }

        // GET
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var grade = _db.Grades.Find(id);

            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult DeletePost(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var grade = _db.Grades.Find(id);

            if (grade == null)
            {
                return NotFound();
            }

            _db.Grades.Remove(grade);
            _db.SaveChanges();
            TempData["success"] = "Grade deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

VirtualSchoolServiceApp/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using VirtualSchoolServiceApp.Data;
using VirtualSchoolServiceApp.Models;

namespace VirtualSchoolServiceApp.Controllers
{
    [Authorize(Roles = "Administrator, Teacher, Student, Parent")]
    public class SubjectController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostEnvironment;

        public SubjectController(ApplicationDbContext db, IWebHostEnvironment hostEnvironment)
        {
            _db = db;
            _hostEnvironment = hostEnvironment;

        }
        public IActionResult Index()
        {
            IEnumerable<Subject> objSubjectsList = _db.Subjects.Include(s => s.Teacher).ThenInclude(t => t.User);
            return View(objSubjectsList);
        }

        public IActionResult SubjectGrades(int? id)
        {
            return View();
        }

        // GET
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["Teachers"] = new SelectList(_db.Set<Teacher>().Include(x => x.User), "Id", "User");
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Subject obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"files\subjects");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.ContentOfEducation != null)
                    {
                        var oldFilePath = Path.Combine(wwwRootPath, obj.ContentOfEducation.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ContentOfEducation = @"\files\subjects\" + fileName + extension;
                }
                _db.Subjects.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Subject created successfully";
                return RedirectToAction("Index");
            }
            ViewData["Teachers"] = new SelectList(_db.Set<Teacher>().Include(x => x.User), "Id", "User");
            return View(obj);
        }

        // GET
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var subject = _db.Subjects.Find(id);

            if (subject == null)
            {
                return NotFound();
            }
            ViewData["Teachers"] = new SelectList(_db.Set<Teacher>().Include(x => x.User), "Id", "User");
            return View(subject);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Teacher")]
        public IActionResult Edit(Subject obj, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"files\subjects");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.ContentOfEducation != null)
                    {
                        var oldFilePath = Path.Combine(wwwRootPath, obj.ContentOfEducation.TrimStart('\\'));
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ContentOfEducation = @"\files\subjects\" + fileName + extension;
                }
                _db.Subjects.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Subject edited successfully";
                return RedirectToAction("Index");
            }
            ViewData["Teachers"] = new SelectList(_db.Set<Teacher>().Include(x => x.User), "Id", "User");
            return View(obj);
        }

        // GET
        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var subject = _db.Subjects.Find(id);

            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult DeletePost(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var subject = _db.Subjects.Find(id);

            if (subject == null)
            {
                return NotFound();
            }
            string wwwRootPath = _hostEnvironment.WebRootPath;

            if (subject.ContentOfEducation != null)
            {
                var oldFilePath = Path.Combine(wwwRootPath, subject.ContentOfEducation.TrimStart('\\'));
                if (System.IO.File.Exists(oldFilePath))
                {
                    System.IO.File.Delete(oldFilePath);
                }
            }

            _db.Subjects.Remove(subject);
            _db.SaveChanges();
            TempData["success"] = "Subject deleted successfully";
            return RedirectToAction("Index");
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAllGrades(int? id)
        {
			var user = User.Identity.Name;
			var gradeList = _db.Grades.Include(g => g.Student).ThenInclude(s => s.User).Where(g => g.SubjectId == id);
			ApplicationUser applicationUser = _db.ApplicationUsers.Include(a => a.Student).First(u => u.UserName == user);
            if (applicationUser != null && applicationUser.IsStudent)
            {
                gradeList = _db.Grades.Include(g => g.Student).ThenInclude(s => s.User).Where(g => g.SubjectId == id && g.StudentId == applicationUser.Student.Id);
            }
			
            return Json(new { data = gradeList });
        }

        #endregion
    }
}

VirtualSchoolServiceApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Data;
using VirtualSchoolServiceApp.Data;
using VirtualSchoolServiceApp.Models;

namespace VirtualSchoolServiceApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
	{
		private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

		public UsersController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
		{
			_db = db;
            _userManager = userManager;

		}
		public IActionResult Index()
		{
			return View();
		}

        // GET
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ApplicationUser obj)
        {
            if (ModelState.IsValid)
            {
				//_db.ApplicationUsers.Add(obj);
                var role = "Administrator";
                if (obj.IsStudent)
                {
                    Student student = new()
                    {
                        User = obj
                    };
                    _db.Students.Add(student);
                    role = "Student";
				}
                if (obj.IsTeacher)
                {
                    Teacher teacher = new()
                    {
                        User = obj
                    };
                    _db.Teachers.Add(teacher);
                    role = "Teacher";
                }
				if (obj.IsParent)
				{
					Parent parent = new()
					{
						User = obj
					};
					_db.Parents.Add(parent);
                    role = "Parent";
				}

                var existingUser = await _userManager.FindByEmailAsync(obj.Email);

                if (existingUser == null)
                {
                    await _userManager.CreateAsync(obj, "Qwerty12#@.");
                    if (!string.IsNullOrWhiteSpace(role))
                    {
                        await _userManager.AddToRoleAsync(obj, role);
                    }
                }
				_db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(obj);
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var usersList = _db.ApplicationUsers;
            return Json(new { data = usersList });
        }

        [HttpDelete]
        public IActionResult Delete(string? id)
        {
            var obj = _db.ApplicationUsers.Find(id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }

            _db.ApplicationUsers.Remove(obj);
            _db.SaveChanges();

            return Json(new { success = true, message = "Delete Successful." });
        }
        #endregion
    }
}

VirtualSchoolServiceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VirtualSchoolServiceApp</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/VirtualSchoolServiceApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/datetime/1.2.0/css/dataTables.dateTime.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Classes" asp-action="Index">Classes</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrator") || this.User.IsInRole("Student") || this.User.IsInRole("Teacher") || this.User.IsInRole("Parent"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subjects</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Annoucement" asp-action="Index">Annoucements</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Administrator") || this.User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Grade" asp-action="Index">Grades</a>
                            </li> 
                        }
                        @if (this.User.IsInRole("Parent") || this.User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">Messages</a>
                            </li> 
                        }

                        @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                    @*<form class="d-flex">
                    <input class="form-control me-sm-2" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.datatables.net/datetime/1.2.0/js/dataTables.dateTime.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>